name: Package
run-name: Package ${{ github.ref_name }} as ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Release version (e.g. 5.5.1-rc1)

jobs:
  package:
    name: Package

    env:
      PHP_EXTENSIONS: none, ctype, curl, dom, fileinfo, intl, json, libxml, mbstring, mysqli, openssl, pgsql, simplexml, tokenizer, xml, xmlwriter, zip
      PHP_INI_VALUES: memory_limit=-1, assert.exception=1, zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: ${{ env.PHP_EXTENSIONS }}
          ini-values: ${{ env.PHP_INI_VALUES }}
          tools: composer

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install ant 1.7
        run: |
          curl -s -O http://archive.debian.org/debian-archive/debian/pool/main/a/ant1.7/ant1.7_1.7.1-7_all.deb
          curl -s -O http://archive.debian.org/debian-archive/debian/pool/main/a/ant1.7/ant1.7-optional_1.7.1-7_all.deb
          sudo apt-get -y -qq remove ant
          sudo apt-get -y -qq install libxerces2-java
          sudo dpkg -i ant1.7_1.7.1-7_all.deb
          sudo dpkg -i ant1.7-optional_1.7.1-7_all.deb
          rm *.deb

      - name: Package
        run: ant package -Dversion=${{ inputs.version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            build/test-results/*.zip
            build/test-results/*.tar.gz
          retention-days: 7

      - name: Calculate hashes
        id: hashes
        run: |
          md5sum build/test-results/* | awk '/.zip/ {print "md5_zip=" $1} /.tar.gz/ {print "md5_tgz=" $1}' >> $GITHUB_OUTPUT
          sha256sum build/test-results/* | awk '/.zip/ {print "sha_zip=" $1} /.tar.gz/ {print "sha_tgz=" $1}' >> $GITHUB_OUTPUT

      - name: Publish summary
        run: |
          echo '#### Checksums for revive-adserver-${{ inputs.version }}.zip' >> $GITHUB_STEP_SUMMARY
          echo ' * sha256: ${{ steps.hashes.outputs.sha_zip }}' >> $GITHUB_STEP_SUMMARY
          echo ' * md5: ${{ steps.hashes.outputs.md5_zip }}' >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo '#### Checksums for revive-adserver-${{ inputs.version }}.tar.gz' >> $GITHUB_STEP_SUMMARY
          echo ' * sha256: ${{ steps.hashes.outputs.sha_tgz }}' >> $GITHUB_STEP_SUMMARY
          echo ' * md5: ${{ steps.hashes.outputs.md5_tgz }}' >> $GITHUB_STEP_SUMMARY
